services:
  db:
    image: postgres:13
    restart: always
    container_name: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: travel
